# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            [Change the Game]({{ site.url}}/public/logo1.png)
tagline:          Political and Organizing Data Training for Communities of Color
description:      'Political and Organizing Data Training for Communities of Color'
url:              http://changethegame.io/
baseurl:          /

#author:
#  name:           'Author'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

#github:
#  repo:           https://github.com/poole/hyde
