# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Change the Game
tagline:          Political and Organizing Data Training for Communities of Color
description:      'Political and Organizing Data Training for Communities of Color'
url:              https://changethegame.io/
baseurl:          ""

#author:
#  name:           'Author'
  # url:            https://twitter.com/mdo

paginate:         6

# Custom vars
version:          0.0.2

#github:
#  repo:           https://github.com/poole/hyde
